### ISSUE TITLE
EU Budget vailable in percentage but not nrelated value

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#244] opened 2021-07-12 14:19 UTC
https://kohesio.eu/projects/Q2907460

EU Budget vailable in percentage but not nrelated value

**Comment by madewild** [comment] 2021-07-12 14:32
Yes we are aware of this, it's because we imported the average co-financing rate from the priority axis but this is not ideal.
Duplicate of https://github.com/ec-doris/kohesio-data-import/issues/122 so closing.

**Closed by madewild** 2021-07-12 14:32 UTC
