### ISSUE TITLE
putting loader in beneficiary page

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#289] opened 2021-12-18 14:43 UTC
Some search requests are slow, because we have a lot of beneficiaries, I suggest putting a loader as in the project page

**Comment by madewild** [comment] 2021-12-18 14:55
Why not, but why is it faster for projects although we have many more projects than beneficiaries? Just trying to understand the cause...

**Comment by madewild** [comment] 2021-12-20 10:24
Maybe can be solved by better cache?

**Comment by raphdom** [comment] 2022-01-31 09:45
@D063520 we could close it because you already improve the cache on beneficiary?

**Comment by D063520** [comment] 2022-01-31 11:02
I'm still for putting a loader ... I mean it is the same as in the project page ....

**Comment by madewild** [comment] 2022-01-31 11:12
Indeed let's harmonise. @raphdom I let you reassign

**Comment by raphdom** [comment] 2022-02-01 22:02
Now we have the loading feature in the beneficiaries list. Can you test, please?

**Comment by madewild** [comment] 2022-02-02 06:08
Perfect!

**Closed by madewild** 2022-02-02 06:08 UTC
