### ISSUE TITLE
Footer - side effect

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#403] opened 2022-02-13 20:14 UTC
Check with Max what we should do

**Comment by madewild** [comment] 2022-02-14 06:19
Linked to #298

**Comment by madewild** [comment] 2022-02-14 20:33
@raphdom what is the "side effect"? or is it just about adding the correct info to the footer? in this case I will treat as a duplicate of #298 and close this one.

**Closed** 2022-02-15 08:17 UTC
