### ISSUE TITLE
Add copyright mention to all image visualisations

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#241] opened 2021-07-12 13:52 UTC
Is the copyright message on photos for the final verison only?

**Comment by madewild** [comment] 2021-07-12 13:54
Not sure I understand the question. On https://kohesio.eu/projects/Q139379 for instance, there is the copyright info below the image. You would like to have it on the photo itself?

**Comment by gachpas** [comment] 2021-07-12 13:57
when clicking to open the picture, there is no copyright below; just when seeing it as part of the prokect fiche or project audio-visual collection.

**Comment by madewild** [comment] 2021-07-12 13:58
@raphdom could we replicate what you did on https://kohesio.eu/projects (audio-visual tab) to have it also on https://ec.europa.eu/regional_policy/rest/projects/upload/regio_standard_153_4078_mellisim_image.jpg ?

**Comment by raphdom** [comment] 2021-09-21 09:29
@madewild  Should be the copyright or the title of the project? In project details we have the copyright below the image but in the audiovisual we have the title of the project inside the image. The information about the copyright I have it on project details but if you need to put in the list we need to ask to add in the API.

**Comment by madewild** [comment] 2021-09-21 09:31
Sorry for the confusion, it's indeed the copyright info we need.
@D063520 or @AlyHdr can you add this to the API?

**Comment by madewild** [comment] 2021-09-22 09:41
Sorry I was confused about this issue, I will clarify again:

- on https://kohesio.eu/projects/Q139379 we have the copyright info "Mellisim & Mellisense" under the image which is fine
- but when clicking on the picture to enlarge it, we see this:

![open_pic](https://user-images.githubusercontent.com/942488/134320645-2c12960c-0723-4532-9933-0e3848fb4417.png)

- so in this open image, could we add a ribbon like:

![pic_ribbon](https://user-images.githubusercontent.com/942488/134320809-e8989b08-c495-493d-a378-459c2a7d7ad1.png)

but with the copyright info "Mellisim & Mellisense" inside instead of the project name?

@raphdom does this make sense?
@D063520 and @AlyHdr no change needed in the API in the end...

**Comment by raphdom** [comment] 2021-09-22 10:49
normally I've fixed on page details with the copyright that we already have in the API results:
![image](https://user-images.githubusercontent.com/5124917/134330529-78b1c2d2-b117-4844-8687-c38a89c42eb8.png)
but in project list I put(for now) the title, because we don't have the copyright in the API results:
![image](https://user-images.githubusercontent.com/5124917/134330584-39ec3f4a-aaa0-468c-ad7a-19ddaa6c9ade.png)
When @D063520 or @AlyHdr add this in the API response I will change it to the copyright.

Sorry about the confusion....

**Comment by D063520** [comment] 2021-09-22 11:32
We are not able to make this until merge ... basically the problem is that this data is in the reefied part which we are not indexing currently .... we plan to do it but we are not there yet ....

**Comment by madewild** [comment] 2021-09-22 11:36
ok no problem, @gachpas can you already check on the project detail page ?
for the result list we postpone until next release

**Comment by gachpas** [comment] 2021-09-22 11:48
Hello @madewild , for me the part that is ready is fine. 
The only thing is....I am not sure whether, from a legal point of view, we are obliged to have the copyright symbol before the name?
Do you have experience with that aspect?
Thanks and kr,
Pascal

**Comment by madewild** [comment] 2021-09-23 05:24
"The symbol is widely recognized but, under the Berne Convention, is no longer required in most nations to assert a new copyright." (https://en.wikipedia.org/wiki/Copyright_symbol)
But why not, we can add it beforme the name to clarify it's the credit and not the title or something else...

**Comment by gachpas** [comment] 2021-09-23 06:49
Hello @madewild , I fully agree...it would clarify what the mention is ;)

**Comment by madewild** [comment] 2021-11-30 14:35
@D063520 what's the status of this?

**Comment by D063520** [comment] 2021-12-10 10:58
this is done. Can you check and close if fine?

**Comment by madewild** [comment] 2021-12-10 11:02
on https://dev.kohesio.eu/projects/Q139379 it's perfect
but on https://dev.kohesio.eu/projects if you click on the photo you still get the title "MELLISEN: continuous blood glucose measurement arm" over the photo instead of the copyright info...

**Comment by madewild** [comment] 2021-12-10 11:02
![cr](https://user-images.githubusercontent.com/942488/145564086-a0332199-a6d4-4c7b-8f05-f683555cb60d.png)

**Comment by D063520** [comment] 2021-12-10 11:04
It's because when you click there what is rendered is not the copyright but the title of the project ....

**Comment by madewild** [comment] 2021-12-13 13:20
@D063520 so what we need is the add the copyright information also to the image api: https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/project/image?offset=0&limit=15

**Comment by madewild** [comment] 2021-12-13 13:22
(to replace the title by the copyright info)

**Comment by D063520** [comment] 2021-12-13 13:32
Added
![Uploading Screenshot 2021-12-13 at 14.32.25.png…]()

**Comment by D063520** [comment] 2021-12-13 13:33
<img width="1680" alt="Screenshot 2021-12-13 at 14 33 10" src="https://user-images.githubusercontent.com/10883585/145821722-abe0d6b3-ba48-462c-b19e-ddc26d775c9c.png">

**Comment by madewild** [comment] 2021-12-13 15:53
sorry @D063520 I was mistaken we need the copyright info in https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/project?offset=0&limit=15 :(

**Comment by D063520** [comment] 2021-12-13 17:10
<img width="1680" alt="Screenshot 2021-12-13 at 18 10 36" src="https://user-images.githubusercontent.com/10883585/145857140-a90f1a7c-c2a7-49d6-93c2-732c2c84218f.png">

**Comment by madewild** [comment] 2021-12-13 19:04
@raphdom is this ok for you?

**Comment by raphdom** [comment] 2021-12-14 08:45
@max and @D063520 it is fine. going to change, thanks

**Comment by raphdom** [comment] 2021-12-14 17:14
done, you can test it on dev

**Comment by madewild** [comment] 2021-12-14 18:19
great, @gachpas can you test one last time in dev before we close?

**Closed** 2021-12-16 09:20 UTC
Labels: test requested
