### ISSUE TITLE
Mobile version - rendering menu

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#246] opened 2021-07-12 14:57 UTC
See search in menus
![IMG_9118](https://user-images.githubusercontent.com/74774446/125309651-3743eb00-e332-11eb-8b24-25acfec735c3.PNG)

**Comment by madewild** [comment] 2021-11-30 14:41
cannot reproduce, @gachpas can you clarify the actual issue? maybe depending on the resolution of the screen...

**Comment by gachpas** [comment] 2021-11-30 15:48
Hello @madewild , I still have the same issue with iphone 7.

**Comment by madewild** [comment] 2021-11-30 15:56
the issue is only the spyglass icon over the "e" of Projects? Is your zoom normal?

**Comment by gachpas** [comment] 2021-11-30 16:00
Yes it is. No zoom.

**Comment by madewild** [comment] 2021-11-30 16:03
so only happening on small screens... will see if there is a fix

**Comment by gachpas** [comment] 2021-11-30 16:07
I thought that the design was repsonsive?!?

**Comment by madewild** [comment] 2021-11-30 16:15
It is. You can open kohesio.eu on a laptop with Chrome, press F12 then click the mobile icon in the toolbar. We are responsive and this is how we render on different phone sizes (S - M - L)
![mobile_s](https://user-images.githubusercontent.com/942488/144085044-d9ffb253-7e4c-4ec0-a0fc-e38975986b63.png)
![mobile_m](https://user-images.githubusercontent.com/942488/144085060-e676172e-829e-46bf-b9d6-718315b1b24f.png)
![mobile_l](https://user-images.githubusercontent.com/942488/144085079-63986465-e570-478d-bb55-f3a4604cddd5.png)

But responsive does not mean that it is perfectly adapted to every phone size...

**Comment by gachpas** [comment] 2021-12-01 08:45
Hello @madewild , when testing mobile version I always do with a mobile, as it is live conditions and curiously it defers from the testing you can do with Chrome (with same definition). The size of Iphone 7 is quite standard, so it should work properly.
Is there a possibility to align the title on the left and/or reduce the font size for the title?
Thanks and kr, Pascal

**Comment by raphdom** [comment] 2021-12-09 14:58
In fact we had another problem, this empty space on the left was the missing logo. Now the logo is there but I hide the search button is small screens. It will appear after 400px. This is not critical because in the homepage we have the search of the projects below the header. Can you check if it is okay now @gachpas and @madewild

**Comment by madewild** [comment] 2021-12-09 15:07
I let @gachpas do it ;)

**Comment by gachpas** [comment] 2021-12-09 16:26
@madewild , @raphdom , as a standard user, I am not sure that I will have the reflex to turn my mobile in landscape mode to be able accessing the search, when being on a project or beneficiary page. Having to go back to the home page to be able searching does not seem natural/convenient to me either. If there is no other possibility that the one you propose, I would let the final decision to @AThollard  for this one ;)

**Comment by raphdom** [comment] 2021-12-10 07:38
@gachpas @madewild @AThollard. We need a threshold when we talk about screen sizes, and I've put the threshold in 350px because this cover most of the devices (see this list: https://mediag.com/blog/popular-screen-resolutions-designing-for-all/). @gachpas can you confirm that doesn't work in your iphone 7, should work and see the search button?

**Comment by gachpas** [comment] 2021-12-10 09:47
@raphdom , not sure what you mean by working ;) 
when going to the project homepgae, I now do not see any search possibility, except if I turn my phone in landscape mode

**Comment by raphdom** [comment] 2021-12-10 10:03
it is weird because normally the iphone 7 has the resolution of 375px(viewport), and I have put the threshold in 350px. I don't have a Iphone 7 to test, but if I test in the browser I can see that it is working. Can you try to send a screenshot of the screen to me, just to understand what is happen. Thank you @gachpas

**Comment by gachpas** [comment] 2021-12-10 10:11
That's why I always try to test with the phone instead of simulating ;)....hereis a screenshot:
 
![6C69010D-0B84-4354-8D92-9CB016816EE9](https://user-images.githubusercontent.com/74774446/145556783-6e0b8e45-a8c1-4891-a3b0-c6cd7a459e0d.png)

**Comment by raphdom** [comment] 2021-12-13 13:20
Okay, in this case it means that your mobile is not greater than 350px which is a bit weird that we have the specifications of the iphone 7 pointing to 375px of the viewport. Can you check if you have a zoom in safari applied or you are in 100%? Thank you @gachpas

**Comment by madewild** [comment] 2021-12-13 13:37
@gachpas could you check http://whatismyscreenresolution.net/ on your iPhone? :)

**Comment by madewild** [comment] 2021-12-13 14:12
we checked with @gachpas and his actual resolution is 320x568px :-/
no zoom in safari...

**Comment by raphdom** [comment] 2021-12-13 15:54
Then I will propose to postponed this small improvement to small size of screens, I will decrease the font-size, but need more time to cross check with other resolutions and sizes.

**Comment by madewild** [comment] 2021-12-20 10:01
If we enable global search on all pages at the top, then we can remove the custom project search and solve this issue :)

**Comment by raphdom** [comment] 2022-01-31 07:07
We will change completely the header with the new ECL look and feel, I suggest to postponed this issue for the release that we will implement the ECL

**Comment by gachpas** [comment] 2022-01-31 16:39
@madewild , so this version is the one for 17th March, correct?

Thansk and kr

**Comment by madewild** [comment] 2022-01-31 16:58
Release planned for March 3: https://github.com/ec-doris/kohesio.eu/milestone/12

**Comment by raphdom** [comment] 2022-02-16 20:48
For this, I don't think that make more sense as we revamp the entire menu, we can close it?

**Comment by madewild** [comment] 2022-02-16 20:54
Yes indeed, should look like this on @gachpas phone now:
![iphone7](https://user-images.githubusercontent.com/942488/154355206-d02d5866-6575-4cab-a305-37e1bb18354a.png)

**Closed by madewild** 2022-02-16 20:54 UTC
Labels: mobile

**Comment by gachpas** [comment] 2022-02-17 08:57
@madewild , indeed on the search element, it is ok on mobile :)
