### ISSUE TITLE
No program, should be n/a or not displayed 

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#315] opened 2022-01-28 07:45 UTC
https://dev.kohesio.eu/projects/Q2900235

<img width="1680" alt="Screenshot 2022-01-28 at 08 44 04" src="https://user-images.githubusercontent.com/10883585/151507091-3f2df5f6-e03c-4657-b235-3361f576a199.png">

**Comment by madewild** [comment] 2022-01-28 07:48
Should indeed be n/a.
Strange it should have been fixed by https://github.com/ec-doris/kohesio.eu/issues/252
Regression?

**Comment by svili** [comment] 2022-01-28 08:03
The problem was that there was programLabel but no infoRegioUrl so no link. Fixing.

**Closed** 2022-01-28 10:26 UTC

**Comment by madewild** [comment] 2022-01-28 10:35
Now there is a programme for the same project, strange...
