### ISSUE TITLE
loosing navigation when going back

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#249] opened 2021-07-12 15:18 UTC
It is also a point that we have already discussed: when selecting some sorting (for instance in the beneficiaries list), then applying some filtering, I arrive to a list that I want to consult. However, if I open a project and go back, I have lost my selection, which is not at all user friendly.

**Comment by madewild** [comment] 2021-07-12 16:33
You should use the "back" button of the browser and not the breadcrumb, and the filters are kept.
@gachpas can you confirm it works?

**Comment by gachpas** [comment] 2021-07-13 07:54
Hello @madewild , it works on laptop but not on mobile.

**Comment by madewild** [comment] 2021-07-13 07:59
@raphdom anything we can do on mobile?

**Comment by raphdom** [comment] 2021-09-21 09:38
So, the problem here is not the mobile, the sort feature is not persisted even on desktop, the filters are but the sort non. @madewild maybe we can close this issue and open another one to persist the sort in projects and beneficiaries list.

**Comment by madewild** [comment] 2021-09-21 10:00
@gachpas could you clarify what you mean by "I have lost my selection"? you mean the filters or the sorting order? is the behaviour diffrent on desktop and mobile?

**Comment by raphdom** [comment] 2021-09-21 11:25
@madewild and @gachpas. Now the sort is persisted, even if you refresh the page or use the back button from the detail page you will not lose the sort anymore.

**Comment by madewild** [comment] 2021-09-21 12:34
Great! @gachpas can you confirm the issue is solved now?

**Comment by gachpas** [comment] 2021-09-21 13:52
@madewild, great! It works ;)

**Comment by madewild** [comment] 2021-09-21 14:26
perfect, closing

**Closed by madewild** 2021-09-21 14:26 UTC
Labels: mobile
