### ISSUE TITLE
connecting projects with beneficiaries

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#210] opened 2021-03-12 13:08 UTC
Currently it is possible to navigate from the beneficiaries to the projects. But in the project website the beneficiary is only indicated as a string. I think it would make sense to add a link from the project page to the corresponding beneficiary page.

**Comment by madewild** [comment] 2021-06-22 12:44
duplicate of #221

**Closed by madewild** 2021-06-22 12:44 UTC
Labels: enhancement
