### ISSUE TITLE
Semantic search - matching terms for 'Just transition'

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio.eu#540] opened 2022-02-21 10:33 UTC
In the previous version when searching for 'Just transition' I had the following matching terms 
"inclusive_societies_clean_energy_transitionlow_carbon_economylow_carbon_societyresilient_citiesclimate_justicesustainable_economic_growthclimate_neutralsocially_inclusivetransition_towardresponsible_citizenshipsustainable_lifestylestransition_towards_sustainableterritorial_cohesioninclusive_growthpoverty_reductionpolicy_coherencemultilevel_governancetransformational_changecircular_economiesdecent_workpoverty_alleviationclimate_neutralitymore_equitablegood_governance"
from https://similarity.cnect.eu/#

Now this search does not trigger the semantic search.
Have you changed the semantic search corpus? the algorithm?

**Comment by madewild** [comment] 2022-02-21 10:37
Yes we tried to improve the semantic search, cf. https://github.com/ec-doris/kohesio-backend/issues/74
We may have some side effects...
@faustusdotbe can you have a look? but let's not break one thing to make the other work ;)

**Comment by AThollard** [comment] 2022-02-21 11:02
Maybe I can search with 'Transition' only? because 'Just Transition' is a bit artificial even if very relevant for Cohesion Policy context.

**Comment by faustusdotbe** [comment] 2022-02-21 11:36
@AThollard  Do you see those similar words for `just_transition`on similarity.cnect.eu while using the H2020 models (default, first in the dropdown) or the Kohesio one? 

It's not in the vocabulary of the model in the Kohesio one: `KeyError: "Key 'just_transition' not present"`. It might have been in an earlier version but I raised the minimal frequency threshold to filter out some other noise back in December. As discussed here (https://github.com/ec-doris/kohesio-backend/issues/74#issuecomment-1046035037) I think it's going to be difficult to have a perfect model for now, a safer move would be to use a general-purpose model or even go back to the H2020 one. The kohesio data is very noisy when it comes to some project descriptions, and that leads to some problems.

**Comment by madewild** [comment] 2022-02-21 17:20
Closing as duplicate of https://github.com/ec-doris/kohesio-backend/issues/74

**Closed by madewild** 2022-02-21 17:20 UTC
