### ISSUE TITLE
Sharing on social networks

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio.eu#248] opened 2021-07-12 15:05 UTC
We had already discussed that but I cannot remember whether it would be taken into account or not...

so, when using the share, I would expect that the link is copied to be able inserting the post, while at the moment, it just opens the related app.

**Comment by madewild** [comment] 2021-07-12 16:31
Duplicate of #198

**Closed by madewild** 2021-07-12 16:31 UTC
